apiVersion: v1
kind: Pod
metadata:
  name: nginx
  # namespace: apps
  labels:
    app.kubernetes.io/name: dse3101-webapp
spec:
  containers:
  - name: webapp-server
    image: "webapp:latest"
    imagePullPolicy: "IfNotPresent"
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "124Mi"
    ports:
    - containerPort: 80
    env:
      - name: "NGINX_PORT"
        value: "80"
      - name: "NGINX_HOST"
        value: "localhost"
      - name: "NGINX_WEBROOT"
        value: "/var/www/html"
    volumeMounts:
      - name: cache-dir
        mountPath: /var/www/cache
  volumes:
  - name: cache-dir
    emptyDir: {}